### ISSUE TITLE
step1 LOCO=TRUE fixed-effect coeffiecients issue

### ISSUE THREAD

**Issue by tbrunetti** [weizhouUMICH/SAIGE#136]
Hi All,

I recently upgraded SAIGE to version 0.36.2 and when I set LOCO=TRUE in step 1 after feeding in a pre-calculated GRM, I get the following error:

> Error in if (max(abs(alpha - alpha0)/(abs(alpha) + abs(alpha0) + tol.coef)) <  : 
>   missing value where TRUE/FALSE needed
> Calls: fitNULLGLMM ... system.time -> glmmkin.ai_PCG_Rcpp_Binary -> Get_Coef_LOCO

 I am assuming it is because the statement will not return a boolean if the fixed-coeffiecients are NaN:

> iGet_Coef:  1 
> iter from getPCG1ofSigmaAndVector 5
> iter from getPCG1ofSigmaAndVector 5
> iter from getPCG1ofSigmaAndVector 4
> iter from getPCG1ofSigmaAndVector 4
> iter from getPCG1ofSigmaAndVector 4
> iter from getPCG1ofSigmaAndVector 5
> iter from getPCG1ofSigmaAndVector 5
> Tau:
> [1] 1.0000000 0.1116774
> Fixed-effect coefficients:
>             [,1]
> [1,]  2.80069113
> [2,] -0.19913799
> [3,] -0.25627908
> [4,] -0.03757916
> [5,]  0.01759631
> [6,]  0.07063276
> iGet_Coef:  1 
> iter from getPCG1ofSigmaAndVector 1
> iter from getPCG1ofSigmaAndVector 1
> iter from getPCG1ofSigmaAndVector 1
> iter from getPCG1ofSigmaAndVector 1
> iter from getPCG1ofSigmaAndVector 1
> iter from getPCG1ofSigmaAndVector 1
> iter from getPCG1ofSigmaAndVector 1
> Tau:
> [1] 1.0000000 0.1116774
> Fixed-effect coefficients:
>      [,1]
> [1,]  NaN
> [2,]  NaN
> [3,]  NaN
> [4,]  NaN
> [5,]  NaN
> [6,]  NaN

However, not sure why they come out to be NaN especially when the first few iterations come out just fine? I do not have this problem when LOCO=FALSE.

Any suggestions on how to troubleshoot?  I have already made sure that the plink file for calculation the varianceRatio is autosomal snps only.

Thanks!

**Comment by tbrunetti** [comment]
So I printed the result of re.coef which stores the result of getCoefficients_LOCO(Y, X, W, tau, maxiter=maxiterPCG, tol=tolPCG) and the resulting list is all NaN... not sure why?

**Comment by weizhouUMICH** [comment]
Hi, 

Thanks for reporting this error! I don't think it has anything to do with the sparse GRM. Would you sharing providing a more complete log file? 

Thanks!

Wei

**Comment by tbrunetti** [comment]
Thank you for your quick response!  Yes, here is my error file output after running step 1:

> Loading required package: optparse
> Error in if (max(abs(alpha - alpha0)/(abs(alpha) + abs(alpha0) + tol.coef)) <  : 
>   missing value where TRUE/FALSE needed
> Calls: fitNULLGLMM ... system.time -> glmmkin.ai_PCG_Rcpp_Binary -> Get_Coef_LOCO
> Timing stopped at: 2005 3.48 107.5
> Execution halted

And I am attaching my log file here:
[SAIGE_step1_2kLOCO_test_01292020.log](https://github.com/weizhouUMICH/SAIGE/files/4156187/SAIGE_step1_2kLOCO_test_01292020.log)

**Comment by tmatsui2** [comment]
Hi Wei,

I am having a very similar issue as @tbrunetti. Step1 works great for me when LOCO is set to FALSE; but when I set it to TRUE, the fixed coefficients are NaNs and I get the following error:

Error in if (max(abs(alpha - alpha0)/(abs(alpha) + abs(alpha0) + tol.coef)) < :
missing value where TRUE/FALSE needed
Calls: fitNULLGLMM ... system.time -> glmmkin.ai_PCG_Rcpp_Binary -> Get_Coef_LOCO

Do you have any ideas as to what is causing this problem? Thank you very much for your help.
[SAIGE_step1_log.txt](https://github.com/weizhouUMICH/SAIGE/files/4482800/SAIGE_step1_log.txt)

**Comment by weizhouUMICH** [comment]
Hi Takeshi,

Can you please try the version 0.36.5, which is updated on 03/29? I've
fixed an issue for LOCO=TRUE.

Thanks!
Wei

* 0.36.5 (March-29-2020)
** Fix a typo to extract p.value. 0.36.5: fix an issue for LOCO=TRUE. This
issue was introduced when the option minMAFforGRM was introduced.

**Comment by tmatsui2** [comment]
Oh that's great! Is there a docker file for version 0.36.5?

**Comment by weizhouUMICH** [comment]
Yes. wzhou88/saige:0.36.5
Sorry I forgot to update the document.

**Comment by tbrunetti** [comment]
Great, thank you!  I will update to the newest version of SAIGE.  Additionally, I still can't use my own GRM, correct?

**Comment by weizhouUMICH** [comment]
Nice. You may try 0.36.6, which was just updated.
No, GRM cann't be specified yet.
