### ISSUE TITLE
New 3.0.0 version of SPATEST R package does not work with SAIGE

### ISSUE THREAD

**Issue by endrebak** [weizhouUMICH/SAIGE#37]
My colleague gets errors about missing values.

**Comment by anitapandit** [comment]
I had this issue as well. Wanted to post a reply in case others have the same issue. The quick fix is to roll back to an [older version](https://cran.r-project.org/src/contrib/Archive/SPAtest/) of SPATest (I am using 2.0.0 with SAIGE v29 no issues). Compatibility issues should be fixed in a future version of SAIGE, but for those who can't wait, you may want to try this in the meantime.

Below is the error I got when running SAIGE with the newest version of SPATest:
```
Error in SPAtest:::Saddle_Prob_fast(q = qtilde, g = g, mu = mu, gNA = g[NAset],  : 
  argument "output" is missing, with no default
Calls: fitNULLGLMM ... scoreTest_SPAGMMAT_forVarianceRatio_binaryTrait -> <Anonymous>
Execution halted
```

**Comment by carbocation** [comment]
While a real fix is probably to update SAIGE to work with the latest SPAtest library, this is the fix I use in the interim. It's called from bash. I use sudo since R is installed in a way where that makes sense, but if your libs are in your local user directory you may not have to call this with sudo.

```
sudo /usr/bin/env Rscript -<<EOF
list.of.packages <- c('Rcpp', 'RcppArmadillo', 'RcppParallel', 'data.table', 'RcppEigen', 'Matrix', 'optparse', 'devtools')
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

library('devtools')
install_version("SPAtest", version = "2.0.2", repos = "http://cran.us.r-project.org")
EOF
```

**Comment by FloWuenne** [comment]
I am still having issues running SAIGE with SPAtest version 3.0.0, even after the recent commit that was supposed to fix this issue. 

When running the new SAIGE version (SAIGE_0.29.2_R_x86_64-pc-linux-gnu.tar.gz) on the test data set from the wiki, I get the following error:

```
Error in SPAtest:::Saddle_Prob_fast(q = qtilde, g = g, mu = mu, gNA = g[NAset],  : 
  argument "output" is missing, with no default
Calls: fitNULLGLMM ... scoreTest_SPAGMMAT_forVarianceRatio_binaryTrait -> <Anonymous>
Execution halted

```
**Workaround**
A not very elegant workaround for this issue at the moment is to use an older version of SPAtest to run step1 of the SAIGE workflow and then load version 3.0.0 to run the second step. For me this is necessary, as the older version of SPAtest (SPAtest_2.0.2) gives me an error in the step2 of the workflow:

```
Error in SPAtest:::Saddle_Prob_fast(q = qtilde, g = g, mu = mu, gNA = g[NAset],  : 
  unused argument (output = "P")
Calls: SPAGMMATtest ... scoreTest_SAIGE_binaryTrait -> scoreTest_SPAGMMAT_binaryTrait
Execution halted
```

I therefore have 2 versions of SPAtest installed: v2.0.2 and v3.0.0 in different directories. To run step1, I load v2.0.2 from my standard library path. For step2, I added the following to the script for running step2:

```
.libPaths("*path_to_version3.0.0_of_SPAtest*")
library(SPAtest)
.libPaths("*standard_R-_library_path*")
```
this way, SPAtest v3.0.0 is loaded and the standard library path is reset to load all other libraries required by SAIGE. This workaround has worked for me so far but it would obviously nice if this issue could be resolved to just work with v3.0.0 throughout the workflow.

If anybody can reproduce the error or can let me know a more elegant way to fix this, I would highly appreciate it.

**Comment by weizhouUMICH** [comment]
Sorry for the inconvenience! Now the v0.29.3 should work with SPAtest 3.0.0

**Comment by FloWuenne** [comment]
Thanks for trying to fix it but I am still getting the same error when only using SPAtest 3.0.0:

While running step1:

```
Error in SPAtest:::Saddle_Prob_fast(q = qtilde, g = g, mu = mu, gNA = g[NAset],  : 
  argument "output" is missing, with no default
Calls: fitNULLGLMM ... scoreTest_SPAGMMAT_forVarianceRatio_binaryTrait -> <Anonymous>
Execution halted
```

I downloaded the new version and installed it using R CMD INSTALL. Any guesses why it is still not working?

**Comment by weizhouUMICH** [comment]
This is quite strange, because I have put output="P" in the file in new version

https://github.com/weizhouUMICH/SAIGE/blob/master/R/SAIGE_SPATest.R

**Comment by FloWuenne** [comment]
Could you try running the new version on the test data supplied with the package to see if it gives the same error? I retried today to make sure I have the newest version installed and I still get this problem in step1. Below is my R sessionInfo() to let you know which packages are loaded. I am running SAIGE on a  network cluster.

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/intel2016.4/r/3.4.3/lib64/R/lib/libR.so
LAPACK: /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/intel2016.4/r/3.4.3/lib64/R/modules/lapack.so

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SPAtest_2.0.2 SAIGE_0.29.3 

loaded via a namespace (and not attached):
[1] compiler_3.4.3     Matrix_1.2-14      Rcpp_0.12.18       grid_3.4.3        
[5] RcppParallel_4.4.1 lattice_0.20-35
```

**Comment by FloWuenne** [comment]
Yes you are obviously right, I did not catch that mistake, thanks for pointing it out. In this instance it loaded the old version of SPAtest  for some reason. 

I just reinstalled SPAtest_v3.0.0 and then rerun SAIGE  and it now works without a problem! 

Thanks for the fix and this issue can be closed now as it has been fixed!
